# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ipizza-omniauth-provider}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Priit Haamer"]
  s.date = %q{2011-04-30}
  s.description = %q{      Integrates iPizza authentication to your rails app almost effortlessly.
}
  s.email = %q{priit@fraktal.ee}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "init.rb",
     "ipizza-omniauth-provider.gemspec",
     "lib/ipizza_omniauth_provider.rb",
     "lib/omniauth/strategies/ipizza.rb"
  ]
  s.homepage = %q{http://github.com/priithaamer/ipizza-omniauth-provider}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{iPizza authentication strategy provider for Omniauth}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ipizza>, ["= 0.4.2"])
    else
      s.add_dependency(%q<ipizza>, ["= 0.4.2"])
    end
  else
    s.add_dependency(%q<ipizza>, ["= 0.4.2"])
  end
end

